
CREATE TABLE tbProfile (
    id INT GENERATED BY DEFAULT AS IDENTITY START WITH 1 NOT NULL,
    nome_completo VARCHAR(50) NOT NULL,
    cpf: VARCHAR(20) NOT NULL,
    data_nascimento DATE,
    PRIMARY KEY (id) 
);